export const strategies = [
  {
    key: "glif",
    title: "GLIF Infinity Pool",
    ticker: "iFIL",
    logo: "/glif.webp",
    about: "",
    address: "",
  },
  {
    key: "stfil",
    title: "STFIL",
    ticker: "stFIL",
    logo: "/stfil.webp",
    about: "",
    address: "",
  },
  {
    key: "collectif",
    title: "CollectifDAO",
    ticker: "cIFIL",
    logo: "/collectif-dao.webp",
    about: "",
    address: "",
  },
  {
    key: "repl",
    title: "Repl",
    ticker: "pFIL",
    logo: "/repl.webp",
    about: "",
    address: "",
  },
  {
    key: "sft",
    title: "SFT Protocol",
    ticker: "SFT",
    logo: "/sft-protocol.webp",
    about: "",
    address: "",
  },
  {
    key: "filet",
    title: "Filet Finance",
    ticker: "nFIL",
    logo: "/filet-finance.webp",
    about: "",
    address: "",
  },
];
